# set these two to take advantage of the new container based builds
# https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/
sudo: false
dist: trusty
language: scala
scala:
   - 2.12.2
jdk:
   - oraclejdk8
   - openjdk8
